### ISSUE TITLE
Structures not spawning (possible config bug?)

### ISSUE THREAD

**Issue by Lictor000** [LogicTechCorp/NetherEx-Archive#97] opened 2018-06-23 13:19 UTC
After over 3 hours of flying in the nether in different new worlds,  and changing their rarity values in the config file to pretty high values (up to 200, or lower and turning to false the superrare setting) I'm pretty confident that there's something preventing spawn of some structures like the pigtificates villages, temples of the torrid wastelands, all structures of artic abyss and probably some minor grave structure (never found one the single chest graves without mobspawner for instance, but didn't search for those that hard).
This I believe could be related to the config itself, since in the config GUI in game the Hell and Torrid Wastelands settings are blank and when I modify the rarity of the fungi temples with spore creepers it just starts popping around many ghast castles.
![2018-06-23_14 24 45](https://user-images.githubusercontent.com/39945124/41809975-a83136d4-76f6-11e8-969c-9babd8f6d49a.png)
![2018-06-23_14 24 49](https://user-images.githubusercontent.com/39945124/41809977-a9606fac-76f6-11e8-8b05-bb2ca6875285.png)
![2018-06-23_15 03 37](https://user-images.githubusercontent.com/39945124/41809978-aa8f03de-76f6-11e8-865a-ee8d2092a38e.png)
This is how was edited the config file when I took this screenshot: https://pastebin.com/iTcyyaQg
As you can see the Ghast castle was set to minimum while I was trying to spawn the largest fungi temple, obtaing the opposite result.

Tests were made with latest mod and forge versions (2.1.14.15 and 14.23.4.2705 respectively) and installing only Nether Ex and no other mod on a fresh minecraft install.

**Comment by angelnc1989** [comment] 2018-07-03 17:37
I can confirm this. The only structures that spawn for me are the Ghast Fortress and fossils.

**Comment by beam53** [comment] 2018-07-09 02:54
I can confirm this too. The only structures that i found are: ghast fortrees, graves and waypoints.

Hope this will be fixed as soon as posible.

**Comment by LogicTechCorp** [comment] 2018-07-10 02:43
This is a known issue due to how I spawn the structures. I have been working on a big update that optimizes a bunch of stuff and fixes a lot of bugs. I hope to have it out relatively soon. Also, the config gui for those biomes is supposed to be empty as the values are set in a custom config.

**Comment by Lictor000** [comment] 2018-07-11 13:51
Thanks for your reply.
Yeah I tought the blank config page could be just a coincidence (pigtificates not spawning in the hell biome as they should), but I pointed it out just to be sure.
Looking forward the future update then! This mod on the paper looks as the best nether expansion out there IMHO. Already brings much content despite the present bugs, so it would be awesome to see it fully functional!
Keep up the good work!

**Comment by LogicTechCorp** [comment] 2018-07-25 03:26
This has been fixed in the latest version.

**Closed as completed by LogicTechCorp** 2018-07-25 03:26 UTC
