### ISSUE TITLE
game crash

### ISSUE THREAD

**Issue by tabular09** [LogicTechCorp/NetherEx-Archive#94] opened 2018-06-13 05:54 UTC
hello my game is crashing either due to your mod or ice and fire here is the crash report 
https://paste.dimdev.org/ruzoyexuve.mccrash
thank you for any help you can give

**Comment by LogicTechCorp** [comment] 2018-06-14 07:07
This issue has been fixed by the Ice and Fire dev. See Alex-the-666/Ice_and_Fire/issues/740.

**Closed as completed by LogicTechCorp** 2018-06-14 07:07 UTC

**Comment by AlexModGuy** [comment] 2018-06-15 17:23
@tabular09 
>       | UCHIJAAAAAAAAAAA | thaumcraft                 | 6.1.BETA16                      | Thaumcraft-1.12.2-6.1.BETA16.jar                | None                                     |

this crash is caused by thaumcraft messing with vanilla classes
