### ISSUE TITLE
LootTable Error

### ISSUE THREAD

**Issue by Zarpyk** [LogicTechCorp/NetherEx-Archive#236] opened 2020-05-25 10:51 UTC
When a player enter nether, the server kick the player
"Crash" log: https://gist.github.com/GuerreroCraft61/15b6eb38a938787b5cb77288e6cdb14d

**Comment by Zarpyk** [comment] 2020-05-25 17:45
Other log: https://gist.github.com/GuerreroCraft61/6352971e8c2a45366c2f51d34ac45581

**Comment by LogicTechCorp** [comment] 2020-06-03 06:06
I know where the issue is, I'll fix it when I have time.

**Comment by LogicTechCorp** [comment] 2020-07-01 08:29
This issue will be fixed in the next release.

**Closed as completed by LogicTechCorp** 2020-07-01 08:29 UTC
