### ISSUE TITLE
NetherEx Exception caught

### ISSUE THREAD

**Issue by Blarg23** [LogicTechCorp/NetherEx-Archive#170] opened 2019-06-18 01:39 UTC
Hello there,

We've been running an ATM 3 remix modpack with some other mods thrown in there. The server we host it on has been crashing as of late, and these are the crash logs that have resulted from that. I honestly do not know what could be causing the issue as we have not gone all to crazy with the Mod itself. Any information you need I can get.

 - Alex L.

[crash-2019-06-17_14.27.28-server.txt](https://github.com/LogicTechCorp/NetherEx/files/3299438/crash-2019-06-17_14.27.28-server.txt)

**Comment by LogicTechCorp** [comment] 2019-06-18 01:56
You have an issue with one of your biome config files. In whatever file, the issue is at line 181 and has to do with an incorrect value for "genProbability".

**Comment by Blarg23** [comment] 2019-06-18 16:49
Hey,

Thanks for the quick reply. How would I go about correcting that? Does that particular value in that config need to match the one in NetherEx or will I need to play around and see what works?

 - Alex

**Comment by LogicTechCorp** [comment] 2019-06-18 17:04
It has to be a number between 0.0 and 1.0. What is it set to?

**Comment by Blarg23** [comment] 2019-06-18 17:23
Welp,

In the hell.json, line 181 only has this "minGenH
In the Torrid Wasteland.json, it has this "genProbability": 1.0,

I've checked the rest of them in the NetherEx config folder and they either don't have a line 181 or it does need a number for it's value.

 - Alex L.

**Comment by LogicTechCorp** [comment] 2019-06-18 18:29
That's strange. Did you modify any of the values in the config files? If so, try running them through https://jsonlint.com. If not, you can delete them and they should regenerate.

**Comment by Blarg23** [comment] 2019-06-18 18:34
I don't believe we've touched them at all. I'll have to try that over lunch and see what happens.

 - Alex L.

**Comment by Blarg23** [comment] 2019-06-18 19:14
Hello,

So, from what I found:

The hell.json got the following error:
Error: Parse error on line 178:
...ability": 0.25,				"minGenH
----------------------^
Expecting 'STRING', got 'undefined'

The nex.cfg got the following error:
Error: Parse error on line 1:
#Configuration file
^
Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[', got 'undefined'

 - Alex L.

**Comment by LogicTechCorp** [comment] 2019-06-18 20:03
Can you send the hell.json over so I can have a look.

**Comment by Blarg23** [comment] 2019-06-18 20:08
I had to convert it to a txt file.

[hell.txt](https://github.com/LogicTechCorp/NetherEx/files/3303226/hell.txt)

**Comment by LogicTechCorp** [comment] 2019-06-18 20:52
It looks like the bottom half of the file got cut off. Just delete it and everything should be fine.

**Comment by Blarg23** [comment] 2019-06-18 21:00
¯\_(ツ)_/¯ I can dig it. I'll give that a go and let you know what happens then.

 - Alex L.

**Comment by Blarg23** [comment] 2019-06-18 21:13
Hey,

Thanks for the help! I started the server back up and no crashes so far. The config itself also looks to be rebuilt and corrected as well. If you don't mind, I'd like to keep this open for a day or two incase we encounter the issue again. Thanks again.

 - Alex L.

**Comment by LogicTechCorp** [comment] 2019-06-18 21:40
No problem.

**Comment by Blarg23** [comment] 2019-06-21 16:35
Hey support,

Bad news bears here. We got the same error again. I checked the config and it again is missing a portion of it's file and looks to be at the same spot. I'll send the config and the latest crash report again. Not certain what could cause a config to remove data like that.

 - Alex L.
[hell (1).txt](https://github.com/LogicTechCorp/NetherEx/files/3315339/hell.1.txt)
[crash-2019-06-21_10.23.56-server.txt](https://github.com/LogicTechCorp/NetherEx/files/3315342/crash-2019-06-21_10.23.56-server.txt)

**Comment by FallenEagle1** [comment] 2019-06-23 18:45
Will be updating the pack in the near future, so if there is something that should done pack side, let me know. For reference, the only pack changes done dealt with netherwart iirc.

**Comment by Blarg23** [comment] 2019-06-29 16:23
Hey guys,

I've noticed that the config itself is writable, so would turning it to read only help prevent this issue?

 - Alex L.

**Comment by LogicTechCorp** [comment] 2019-07-21 05:29
In the upcoming update, a lot has been changed with the config system and this issue should be fixed.

**Closed as completed by LogicTechCorp** 2019-07-21 05:29 UTC
