### ISSUE TITLE
Compatibility with Better Nether ?

### ISSUE THREAD

**Issue by Zygus42** [LogicTechCorp/NetherEx-Archive#181] opened 2019-08-12 08:45 UTC
With the latest version it seems that if I set 
            B:overrideNether=true
then I don't get Better Nether biomes

If I set
            B:overrideNether=false
then I don't get NetherEx biomes

I'm trying to figure out if this is a problem with Better Nether, NetherEx or BiomeTweaker, or if they're just plain incompatible due to the difference in the way they gen biomes.

**Comment by AnnaErisian** [comment] 2019-08-28 23:12
Unsure of the cause, but if it's any help - this is not an issue using the following mods/versions (though I have a lot of others as well, they shouldn't interfere)

- LibEx 1.0.8
- NetherEx 2.0.8
- BetterNether 0.1.8.3
- Biomes O' Plenty 7.0.1

Meaning something between 1.0.8 and 1.0.11 (LibEx) or 2.0.8 and 2.0.12 (NetherEx) is responsible.  For now I'm just going to leave my pack on the old version.

**Comment by capt-slowpoke** [comment] 2019-09-11 22:50
Can confirm. They were working fine together in 2.0.8 for me as well and now I'm seeing only NEX and BoP biomes. Is there a way to add custom biomes from other mods?

**Comment by LogicTechCorp** [comment] 2019-09-11 23:55
This should be resolved in the latest version which is 2.0.14.

**Closed as completed by LogicTechCorp** 2019-09-11 23:55 UTC
