### ISSUE TITLE
Can't get Non-NetherEx mobs to spawn in the Nether

### ISSUE THREAD

**Issue by ScottRadish** [LogicTechCorp/NetherEx-Archive#82] opened 2018-03-11 01:44 UTC
I'm trying to get Magma Monsters from the Magma Monster mod to spawn, but they don't. I can't get the imps from natura, or the spiders from The Erebus. I can't even get the chickens from the Chickens mod to spawn there.

**Comment by LogicTechCorp** [comment] 2018-03-11 03:57
This is a known issue. It has to do with the way I create the config for the mod. I am looking into it and hope to have it fixed in the next big update which is currently being worked on.

**Comment by mccoole** [comment] 2018-04-07 21:20
FYI I tried adding the nether quartz and soul sand chickens into the nex_biome_list.json file and ended up with a reboot loop on my Engineer's Forest 3 server.  NetherEx would throw an exception:

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from NetherEx (nex)
Caused by: java.lang.NullPointerException
	at nex.world.biome.NetherBiomeManager.postInit(NetherBiomeManager.java:152)
	at nex.NetherEx.onFMLPostInitialization(NetherEx.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Thread.java:748)

**Comment by LukeSkywaIker** [comment] 2018-06-03 20:51
I´m trying to spawn abyssalcraft monsters in the Nether via the json but its not working. Though i´m able to spawn above mentioned magma monsters.

**Comment by darchitect7** [comment] 2018-06-08 04:00
Any update on this? Want to include your mod in my pack, but this is a significant issue. Thanks!

**Comment by generrosity** [comment] 2018-06-18 02:11
+1 Thanks for the reference to Chickens - led me to this. Our own workaround in the meantime will likely be 'selling' spawn eggs

**Comment by LogicTechCorp** [comment] 2018-07-25 03:26
This has been fixed in the latest version.

**Closed as completed by LogicTechCorp** 2018-07-25 03:26 UTC
Labels: Minor Bug, Compatibility
