### ISSUE TITLE
Possible issue with mushroom block drops

### ISSUE THREAD

**Issue by Helpbot3000** [LogicTechCorp/NetherEx-Archive#35] opened 2017-07-26 00:27 UTC
Is it intended for elder mushrooms to be harvest-able by explosion?  By this I mean they drop blocks when blown up.  Also, are there plans to add hammers for the other ores, or is it intended for there to only be a golden bone hammer?  Would you add the ability to mine vanilla mushroom blocks with the golden bone axe, as well?  I don't know where to put some of this stuff so I'm putting it here.

Also, what do the pigtificate villages look like?

**Comment by LogicTechCorp** [comment] 2017-07-29 05:44
No, that is not the intended behavior and it has been fixed in the latest version. NetherEx is about improving the Nether and not touching other aspects of Minecraft, so, there is not going to be any other hammers and the Golden Bone Axe is only going to be used with the Elder Mushrooms. The Pigtificate Villages consist of tiny huts made out of Nether Brick.

**Closed as completed by LogicTechCorp** 2017-07-29 05:44 UTC
