### ISSUE TITLE
Crash w/ the Advent of Ascension Mod

### ISSUE THREAD

**Issue by WenXin20** [LogicTechCorp/NetherEx-Archive#136] opened 2019-01-15 01:35 UTC
Forge v14.23.5.2807-1.12.2
NetherEx v2.0.8
LibEx v1.0.8
[Climatic ](https://minecraft.curseforge.com/projects/climatic-biome-placement)v2.6.0

I got this crash while generating a new world using the Climatic World Type.

**[Crash Report](https://gist.github.com/WenXin20/a5ac2590e230e1901a7941ffac7c26bd)**

**Comment by Andyghandi** [comment] 2019-01-22 18:35
Have the same crash, however this wasnt with the climatic biomes mod. I used Terrarium world type when this hapened.

**Comment by WenXin20** [comment] 2019-01-22 18:42
I have the mod [Terrarium](https://minecraft.curseforge.com/projects/terrarium) installed as well, but I think I was creating a world type using Climatic Biomes.

**Comment by LogicTechCorp** [comment] 2019-01-24 00:57
This crash appears to be an issue with entities. Do either of you use a mod that adds entities?

**Comment by WenXin20** [comment] 2019-01-27 04:33
Yeah, I have a lot of mods installed, including one called [BetterNether](https://minecraft.curseforge.com/projects/betternether). Maybe it's related to that?

**Comment by LogicTechCorp** [comment] 2019-01-27 04:58
Can you make a back up of your world and only run LEX and NEX?

**Comment by WenXin20** [comment] 2019-01-27 05:18
I was testing a pack I was making, so I'm not sure which world it was that had NetherEx and crashed, but I'll try to find it.

**Comment by WenXin20** [comment] 2019-01-30 06:37
I think found out that the crash happens when the [Advent of Ascension](https://minecraft.curseforge.com/projects/advent-of-ascension-nevermine) mod is also in the pack. I'll have to confirm tomorrow that it's what causes the crash.

**Comment by WenXin20** [comment] 2019-01-30 16:15
It works again after removing the Advent of Ascension mod.

**Comment by BugmanBugman** [comment] 2019-01-30 21:09
i got this too

**Comment by Tslat** [comment] 2019-01-30 22:07
Hi guys,

Current dev of AoA here (and sole author of everything AoA-1.12+)
I've had this reported once or twice, but I'm unable to do anything with it, as the github source code doesn't match the jar file (the class doesn't even exist in the github source code).
Not to mention the packages aren't even the same, and when I attempt to view the class code in a java decompiler, it comes up as corrupt.

I can't do anything with this until either the jar file is fixed to be viewable so I can see where it's crashing, or the github code actually matches what's in the jar

**Comment by Tslat** [comment] 2019-01-31 05:45
Someone tried to get in contact with Loki for me so we could work out what the issue is (could be AoA, could be a general incompatibility with some types of mods on NetherEx's end).

Unfortunately Loki didn't seem to want to assist, so this one may remain unfixed for a while
https://cdn.discordapp.com/attachments/434160774546456594/540392779713609728/image0.png

**Comment by LogicTechCorp** [comment] 2019-01-31 06:03
Hey, sorry for the silence. This issue is caused by a NPE when I try to get an entity's name from the registry. You can see it [here](https://github.com/LogicTechCorp/NetherEx/blob/3c49180e91f7f9aefed023eeb8aa883bf9c5b305/src/main/java/nex/world/biome/BiomeWrapperNetherEx.java#L105). It is either caused by an entity that isn't registered correctly or doesn't have a correct entity entry.

**Comment by Tslat** [comment] 2019-01-31 06:25
Thanks for the response logic

Any chance you're able to drop me a jar with a logger of the classname prior to that line so I can test?
Saves me having to compile the jar myself just to get that one line.

Maybe I've missed something, but I ran this while standing in the nether:
```
		Biome biome = ev.getWorld().getBiome(ev.getPos());

		for (EnumCreatureType type : EnumCreatureType.values()) {
			for (Biome.SpawnListEntry entry : biome.getSpawnableList(type)) {
				System.out.println(entry.entityClass.toString());
				ResourceLocation location = ForgeRegistries.ENTITIES.getKey(EntityRegistry.getEntry(entry.entityClass));

				if (location == null) {
					System.out.println("NULL");
				}
				else {
					System.out.println(location.toString());
				}
			}
		}
```

and produced this:
```
[STDOUT]: class net.minecraft.entity.monster.EntityGhast
[STDOUT]: minecraft:ghast

[STDOUT]: class net.minecraft.entity.monster.EntityPigZombie
[STDOUT]: minecraft:zombie_pigman

[STDOUT]: class net.minecraft.entity.monster.EntityMagmaCube
[STDOUT]: minecraft:magma_cube

[STDOUT]: class net.minecraft.entity.monster.EntityEnderman
[STDOUT]: minecraft:enderman

[STDOUT]: class net.tslat.aoa3.entity.mobs.nether.EntityEmbrake
[STDOUT]: aoa3:embrake

[STDOUT]: class net.tslat.aoa3.entity.npcs.lottoman.EntityWitheringLottoman
[STDOUT]: aoa3:withering_lottoman

[STDOUT]: class net.tslat.aoa3.entity.misc.EntitySpawnFluffer
[STDOUT]: aoa3:spawn_fluffer_ignore
```


Can't seem to reproduce

**Comment by LogicTechCorp** [comment] 2019-02-02 21:43
@Tslat I've been able to reproduce the issue. I ran the current versions of LEX, NEX, and AoA. I tried looking into both NEX and AoA, but I can't seem to pinpoint the exact cause.

**Comment by LogicTechCorp** [comment] 2019-02-02 22:58
@Tslat I think I found what the issue is. I printed out some information about the mobs to the console and got this:
```
[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:106]: Entity Class: class net.tslat.aoa3.entity.mobs.overworld.fullmoon.EntityNightWatcher
[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:107]: Entity Entry: net.minecraftforge.fml.common.registry.EntityEntryBuilder$BuiltEntityEntry@267e52da
[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:108]: Entity Registry Name: aoa3:night_reaper
[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:109]: Entity Registry Name String: aoa3:night_reaper

[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:106]: Entity Class: class net.tslat.aoa3.entity.mobs.overworld.EntityNightReaper
[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:107]: Entity Entry: null
[15:49:11] [Server thread/INFO] [STDOUT]: [nex.world.biome.BiomeWrapperNetherEx:parse:108]: Entity Registry Name: null
```
The first one is what is expected, but the second one is not and is what is causing the crash. It appears that the EntityEntry for the Night Reaper is null. So, when I use the null entry to get the registry name I get a null ResourceLocation and when I call toString() on the ResourceLocation, the game crashes.

**Comment by Tslat** [comment] 2019-02-02 23:53
Ah... night reaper
Yes this is/was a bugged mob in snapshot 10. It is fixed in code and will be fine in the full release.
With this being the case, you can safely close this bug report. Thanks for the assistance

**Closed as completed** 2019-02-03 00:56 UTC

**Comment by Somebody139** [comment] 2020-08-12 19:28
> Hi guys,
> 
> Current dev of AoA here (and sole author of everything AoA-1.12+)
> I've had this reported once or twice, but I'm unable to do anything with it, as the github source code doesn't match the jar file (the class doesn't even exist in the github source code).
> Not to mention the packages aren't even the same, and when I attempt to view the class code in a java decompiler, it comes up as corrupt.
> 
> I can't do anything with this until either the jar file is fixed to be viewable so I can see where it's crashing, or the github code actually matches what's in the jar

i downloaded the mod from ur website and crashes while set up(java.lang.arrayindexoutofboundsexception 316). i only had 2 mods and those didnt had entities like mobs

**Comment by Somebody139** [comment] 2020-08-12 19:41
if you want from my second account the mods i use with AoA3 v1.12.2(keeps crashing), with 21 mods(without AoA3), i only can give you the error message: Description: Ticking memory connection

java.lang.ArrayIndexOutOfBoundsException: 316
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at net.tslat.aoa3.client.event.ClientEventHandler.onPlayerJoin(ClientEventHandler.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_ClientEventHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at org.lwjgl.input.Keyboard.getKeyName(Keyboard.java:429)
	at net.tslat.aoa3.client.event.ClientEventHandler.onPlayerJoin(ClientEventHandler.java:143)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_115_ClientEventHandler_onPlayerJoin_PlayerLoggedInEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.minecraftforge.fml.common.FMLCommonHandler.firePlayerLoggedIn(FMLCommonHandler.java:575)
	at net.minecraft.server.management.PlayerList.initializeConnectionToPlayer(PlayerList.java:219)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.completeServerSideConnection(NetworkDispatcher.java:255)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher.access$100(NetworkDispatcher.java:72)
	at net.minecraftforge.fml.common.network.handshake.NetworkDispatcher$1.func_73660_a(NetworkDispatcher.java:205)
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:285)

-- Ticking connection --
Details:
	Connection: net.minecraft.network.NetworkManager@4ec56fb4
Stacktrace:
	at net.minecraft.network.NetworkSystem.func_151269_c(NetworkSystem.java:180)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:790)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:279)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1284893552 bytes (1225 MB) / 3741319168 bytes (3568 MB) up to 5726797824 bytes (5461 MB)
	JVM Flags: 2 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G
	IntCache: cache: 0, tcache: 0, allocated: 12, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.5.2847 Optifine OptiFine_1.12.2_HD_U_F5 25 mods loaded, 25 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version           | Source                                         | Signature                                |
	|:------ |:------------------- |:----------------- |:---------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2            | minecraft.jar                                  | None                                     |
	| LCHIJA | mcp                 | 9.42              | minecraft.jar                                  | None                                     |
	| LCHIJA | sampler             | 1.84              | sampler-1.84.jar                               | None                                     |
	| LCHIJA | FML                 | 8.0.99.99         | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | forge               | 14.23.5.2847      | forge-1.12.2-14.23.5.2847.jar                  | None                                     |
	| LCHIJA | xaerominimap_core   | 1.12.2-1.0        | minecraft.jar                                  | None                                     |
	| LCHIJA | damageindicatorsmod | 1.0               | [1.12.2]DamageIndicatorsMod-3.5.1.jar          | None                                     |
	| LCHIJA | aoa3                | 3.3.4             | AoA3-3.3.4.jar                                 | 8bddeac148843f40e0b9f69201be2f4b3071700d |
	| LCHIJA | baubles             | 1.5.2             | Baubles-1.12-1.5.2.jar                         | None                                     |
	| LCHIJA | bettercaves         | 1.12.2            | bettercaves-1.12.2-1.6.0.jar                   | None                                     |
	| LCHIJA | gottschcore         | 1.13.1            | GottschCore-mc1.12.2-f14.23.5.2768-v1.13.1.jar | None                                     |
	| LCHIJA | ironchest           | 1.12.2-7.0.67.844 | ironchest-1.12.2-7.0.72.847.jar                | None                                     |
	| LCHIJA | jei                 | 4.15.0.291        | jei_1.12.2-4.15.0.291.jar                      | None                                     |
	| LCHIJA | lootbags            | 2.5.8.5           | LootBags-1.12.2-2.5.8.5.jar                    | None                                     |
	| LCHIJA | lucky               | 7.6.0             | luckyblock-1.12.2-1.jar                        | None                                     |
	| LCHIJA | mm                  | 1.2               | MerchMod-1.2.jar                               | None                                     |
	| LCHIJA | roguelike           | 1.8.0             | RoguelikeDungeons-1.12.2-1.8.0.jar             | None                                     |
	| LCHIJA | silentlib           | 3.0.13            | SilentLib-1.12.2-3.0.13+167.jar                | None                                     |
	| LCHIJA | scalinghealth       | 1.3.37            | ScalingHealth-1.12.2-1.3.42+147.jar            | None                                     |
	| LCHIJA | treasure2           | 1.12.0            | Treasure2-mc1.12.2-f14.23.5.2768-v1.12.0.jar   | None                                     |
	| LCHIJA | treechopper         | 1.2.4             | TreeChopper-1.12.2-1.2.4.jar                   | None                                     |
	| LCHIJA | uteamcore           | 2.2.4.107         | u_team_core-1.12.2-2.2.4.107.jar               | None                                     |
	| LCHIJA | usefulbackpacks     | 1.5.1.35          | useful_backpacks-1.12.2-1.5.1.35.jar           | None                                     |
	| LCHIJA | warpbook            | 1.12.2-3.3.4      | Warpbook-1.12.2-3.3.4.jar                      | None                                     |
	| LCHIJA | xaerominimap        | 20.20.0           | Xaeros_Minimap_20.20.0_Forge_1.12.jar          | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_20.20.0_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	Profiler Position: N/A (disabled)
	Player Count: 1 / 8; [EntityPlayerMP['cL1cKyB'/1740, l='Minecraft Alive', x=62.50, y=69.00, z=-225.50]]
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_F5
	OptiFine Build: 20191204-141934
	Render Distance Chunks: 8

**Comment by Tslat** [comment] 2020-08-12 20:06
Looks to me like you've gotten versions options.txt mixed up. Delete your options.txt file and it'll regenerate. Also, this is a long-dead github post, make your own if you have a new issue

**Comment by Somebody139** [comment] 2020-08-12 23:48
> Looks to me like you've gotten versions options.txt mixed up. Delete your options.txt file and it'll regenerate. Also, this is a long-dead github post, make your own if you have a new issue

Really? So i do just have to delete options.txt and its fixed? Yeah i am srry for posting this into a dead github-post
