### ISSUE TITLE
Wrong Method behaviour that causes crash on nether generationn

### ISSUE THREAD

**Issue by Davoleo** [LogicTechCorp/NetherEx-Archive#254] opened 2020-09-01 18:59 UTC
Minecraft Version: 1.12.2
Mod Version: 2.1.8

https://github.com/LogicTechCorp/NetherEx/blob/1.12.x/src/main/java/logictechcorp/netherex/world/generation/ChunkGeneratorNetherEx.java#L471

This is the stacktrace that I get when I try to call the vanilla method "findNearestStructure()" to locate Vanilla nether fortresses
![image](https://user-images.githubusercontent.com/24458276/91894429-fa30b600-ec95-11ea-9aff-808aa3da7cc2.png)

This also breaks the `locate` command that prints an error to the chat

**Comment by LogicTechCorp** [comment] 2020-11-03 02:57
I am unable to replicate this crash. Are there any other mods installed besides Metallurgy?

**Comment by Davoleo** [comment] 2020-11-03 17:28
of course it doesn't crash we didn't push broken code to curseforge :/
and we do a specific check when generating the ore that also calls the method findNearestStructure to avoid calling it when NetherEX is present otherwise it crashes, I can provide you a build that doesn't have that patch though if you need it please tell me (my Discord tag is Davoleo#3333)

The check we do in our code
https://github.com/Davoleo/Metallurgy-4-Reforged/blob/03b1252c771a539f33d924ed8dc33cc324710698/src/main/java/it/hurts/metallurgy_reforged/world/spawn/NearFortressSpawn.java#L38-L43

**Comment by Davoleo** [comment] 2020-11-03 17:30
I think you can generate the exception (which doesn't make the game crash but spits out an error in that case) if you use the locate command to locate a nether fortress with only netherEX installed

**Comment by LogicTechCorp** [comment] 2020-11-04 20:45
I was able to find the cause of the crash after some additional testing. NetherEx only generates Nether Fortresses in the default Nether biome, but it turns out that it causes issues when calling certain methods in other biomes. I am going to make it so Nether Fortresses can spawn in any biome which will fix the crash along with some other issues. I am working on other bug fixes and I hope to have the update out sometime next week. I'll close this issue once it is released.

**Comment by LogicTechCorp** [comment] 2020-11-25 03:25
This issue has been fixed in the latest version.

**Closed as completed by LogicTechCorp** 2020-11-25 03:25 UTC
