### ISSUE TITLE
Crash on chunk generating Nether with Sponge?

### ISSUE THREAD

**Issue by NLBlacky** [LogicTechCorp/NetherEx-Archive#141] opened 2019-02-12 00:18 UTC
I've had a few crashes when someone joins the Nether in Project Ozone 3. I made a ticket on the modpacks Github. We expect NetherEx to be causing the issue together with Sponge. I'll link the issue report below in the hope that someone might be able to help me track the issue.

[Link to the issue](https://minecraft.curseforge.com/projects/project-ozone-3-a-new-way-forward/issues/401)

Bit new with linking issues from other Githubs so I posted the link above.

**Comment by LogicTechCorp** [comment] 2019-02-12 01:54
This might be a problem caused by Sponge. See https://github.com/SpongePowered/SpongeForge/issues/2405. Try disabling async lighting and see if the issue still occurs.

**Comment by NLBlacky** [comment] 2019-02-12 01:56
Thanks for the info. I’ll give it a try.

**Comment by keplersj** [comment] 2019-05-11 22:21
I'm getting a crash on server load when NetherEx (2.0.8) is installed with SpongeForge (1.12.2-2825-7.1.6-RC3694.) Seems to occur when the server is generating chunks, while getting the world ready for players. Disabling async-lighting didn't fix the crash.

Crash Log:
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  SpongeCoremod (spongeforge-1.12.2-2825-7.1.6-RC3694.jar)
  AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  ForgelinPlugin (Forgelin-1.8.2.jar)
  Quark Plugin (Quark-r1.5-149.jar)
Contact their authors BEFORE contacting forge

// Quite honestly, I wouldn't worry myself about that.

Time: 5/11/19 10:13 PM
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderException: nex Failed load class: nex.NetherEx
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)
	at net.minecraftforge.fml.server.FMLServerHandler.beginServerLoading(FMLServerHandler.java:98)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStart(FMLCommonHandler.java:333)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:125)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: nex.NetherEx
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at net.minecraftforge.fml.common.ModClassLoader.loadClass(ModClassLoader.java:75)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:539)
	... 31 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 37 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:544)
	at sun.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:219)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:197)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.redirect$onPost$zza000(LoadController.java:553)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:136)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:593)

-- Sponge PhaseTracker --
Details:
	Phase Stack: [Empty stack]
Stacktrace:
	at net.minecraft.server.MinecraftServer.handler$onCrashReport$zjo000(MinecraftServer.java:3975)
	at net.minecraft.server.MinecraftServer.func_71230_b(MinecraftServer.java:889)
	at net.minecraft.server.dedicated.DedicatedServer.func_71230_b(DedicatedServer.java:371)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:558)
	at java.lang.Thread.run(Thread.java:748)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Linux (amd64) version 4.15.0-48-generic
	Java Version: 1.8.0_201, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 50834640 bytes (48 MB) / 536870912 bytes (512 MB) up to 2147483648 bytes (2048 MB)
	JVM Flags: 3 total; -XX:+UseG1GC -Xms512M -Xmx2G
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2836 102 mods loaded, 102 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                        | Version                  | Source                                                      | Signature                                |
	|:----- |:------------------------- |:------------------------ |:----------------------------------------------------------- |:---------------------------------------- |
	| LC    | minecraft                 | 1.12.2                   | minecraft.jar                                               | None                                     |
	| LC    | mcp                       | 9.42                     | minecraft.jar                                               | None                                     |
	| LC    | FML                       | 8.0.99.99                | forge-1.12.2-14.23.5.2836-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | forge                     | 14.23.5.2836             | forge-1.12.2-14.23.5.2836-universal.jar                     | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LC    | spongeapi                 | 7.1.0-4ab0d1a5           | spongeforge-1.12.2-2825-7.1.6-RC3694.jar                    | None                                     |
	| LC    | sponge                    | 1.12.2-7.1.6-SNAPSHOT    | spongeforge-1.12.2-2825-7.1.6-RC3694.jar                    | None                                     |
	| LC    | spongeforge               | 1.12.2-2825-7.1.6-RC3694 | spongeforge-1.12.2-2825-7.1.6-RC3694.jar                    | None                                     |
	| LC    | applecore                 | 3.2.0                    | AppleCore-mc1.12.2-3.2.0.jar                                | None                                     |
	| LC    | appliedenergistics2       | rv6-stable-6             | appliedenergistics2-rv6-stable-6.jar                        | dfa4d3ac143316c6f32aa1a1beda1e34d42132e5 |
	| LC    | jei                       | 4.15.0.268               | jei_1.12.2-4.15.0.268.jar                                   | None                                     |
	| LC    | quark                     | r1.5-149                 | Quark-r1.5-149.jar                                          | None                                     |
	| LC    | autoreglib                | 1.3-28                   | AutoRegLib-1.3-28.jar                                       | None                                     |
	| LC    | baubles                   | 1.5.2                    | Baubles-1.12-1.5.2.jar                                      | None                                     |
	| LC    | bdlib                     | 1.14.3.12                | bdlib-1.14.3.12-mc1.12.2.jar                                | None                                     |
	| LC    | mantle                    | 1.12-1.3.3.49            | Mantle-1.12-1.3.3.49.jar                                    | None                                     |
	| LC    | natura                    | 1.12.2-4.3.2.66          | natura-1.12.2-4.3.2.66.jar                                  | None                                     |
	| LC    | thaumcraft                | 6.1.BETA26               | Thaumcraft-1.12.2-6.1.BETA26.jar                            | None                                     |
	| LC    | twilightforest            | 3.8.689                  | twilightforest-1.12.2-3.8.689-universal.jar                 | None                                     |
	| LC    | tconstruct                | 1.12.2-2.12.0.135        | TConstruct-1.12.2-2.12.0.135.jar                            | None                                     |
	| LC    | codechickenlib            | 3.2.2.353                | CodeChickenLib-1.12.2-3.2.2.353-universal.jar               | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | redstoneflux              | 2.1.0                    | RedstoneFlux-1.12-2.1.0.6-universal.jar                     | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | cofhcore                  | 4.6.2                    | CoFHCore-1.12.2-4.6.2.25-universal.jar                      | None                                     |
	| LC    | cofhworld                 | 1.3.0                    | CoFHWorld-1.12.2-1.3.0.6-universal.jar                      | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalfoundation         | 2.6.2                    | ThermalFoundation-1.12.2-2.6.2.26-universal.jar             | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | thermalexpansion          | 5.5.3                    | ThermalExpansion-1.12.2-5.5.3.41-universal.jar              | 8a6abf2cb9e141b866580d369ba6548732eff25f |
	| LC    | forestry                  | 5.8.1.322                | forestry_1.12.2-5.8.1.322.jar                               | None                                     |
	| LC    | railcraft                 | 12.0.0                   | railcraft-12.0.0.jar                                        | a0c255ac501b2749537d5824bb0f0588bf0320fa |
	| LC    | immersiveengineering      | 0.12-89                  | ImmersiveEngineering-0.12-89.jar                            | 4cb49fcde3b43048c9889e0a3d083225da926334 |
	| LC    | betterwithmods            | 1.12-2.3.20-1027         | BetterWithMods-1.12-2.3.20-1027.jar                         | None                                     |
	| LC    | bibliocraft               | 2.4.5                    | BiblioCraft[v2.4.5][MC1.12.2].jar                           | None                                     |
	| LC    | biomesoplenty             | 7.0.1.2419               | BiomesOPlenty-1.12.2-7.0.1.2419-universal.jar               | None                                     |
	| LC    | botania                   | r1.10-361                | Botania+r1.10-361.jar                                       | None                                     |
	| LC    | ceramics                  | 1.12-1.3.7               | Ceramics-1.12-1.3.7.jar                                     | None                                     |
	| LC    | chameleon                 | 1.12-4.1.3               | Chameleon-1.12-4.1.3.jar                                    | None                                     |
	| LC    | chiselsandbits            | 14.32                    | chiselsandbits-14.32.jar                                    | None                                     |
	| LC    | clumps                    | 3.1.2                    | Clumps-3.1.2.jar                                            | None                                     |
	| LC    | conarm                    | 1.2.3.4                  | conarm-1.12.2-1.2.3.4.jar                                   | 5d5b8aee896a4f5ea3f3114784742662a67ad32f |
	| LC    | cookingforblockheads      | 6.4.70                   | CookingForBlockheads_1.12.2-6.4.70.jar                      | None                                     |
	| LC    | dynmap                    | 3.0-beta-1-129           | Dynmap-3.0-beta-1-forge-1.12.2.jar                          | None                                     |
	| LC    | enderstorage              | 2.4.5.135                | EnderStorage-1.12.2-2.4.5.135-universal.jar                 | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | engineersdoors            | 0.8.0                    | engineers_doors-1.12.2-0.8.0.jar                            | None                                     |
	| LC    | zerocore                  | 1.12.2-0.1.2.8           | zerocore-1.12.2-0.1.2.8.jar                                 | None                                     |
	| LC    | bigreactors               | 1.12.2-0.4.5.66          | ExtremeReactors-1.12.2-0.4.5.66.jar                         | None                                     |
	| LC    | farmingforblockheads      | 3.1.26                   | FarmingForBlockheads_1.12.2-3.1.26.jar                      | None                                     |
	| LC    | forgelin                  | 1.8.2                    | Forgelin-1.8.2.jar                                          | None                                     |
	| LC    | forgemultipartcbe         | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| LC    | microblockcbe             | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                | None                                     |
	| LC    | minecraftmultipartcbe     | 2.6.1.81                 | ForgeMultipart-1.12.2-2.6.1.81-universal.jar                | None                                     |
	| LC    | gendustry                 | 1.6.5.8                  | gendustry-1.6.5.8-mc1.12.2.jar                              | None                                     |
	| LC    | hatchery                  | 2.2.1                    | hatchery-1.12.2-2.2.1.jar                                   | None                                     |
	| LC    | waila                     | 1.8.26                   | Hwyla-1.8.26-B41_1.12.2.jar                                 | None                                     |
	| LC    | immersivepetroleum        | 1.1.9                    | immersivepetroleum-1.12.2-1.1.9.jar                         | None                                     |
	| LC    | immersivetech             | 1.3.10                   | immersivetech-1.12-1.3.10.jar                               | None                                     |
	| LC    | teslacorelib              | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                            | d476d1b22b218a10d845928d1665d45fce301b27 |
	| LC    | industrialforegoing       | 1.12.2-1.12.2            | industrialforegoing-1.12.2-1.12.11-235.jar                  | None                                     |
	| LC    | oreberries                | 0.5.0                    | oreberries-1.12.x-0.5.0.jar                                 | None                                     |
	| LC    | harvestcraft              | 1.12.2zb                 | Pam's+HarvestCraft+1.12.2zc+The+7mm+Kidney+Stone+Update.jar | None                                     |
	| LC    | rustic                    | 1.1.0                    | rustic-1.1.0.jar                                            | None                                     |
	| LC    | integrationforegoing      | 1.12.2-1.9               | IntegrationForegoing-1.12.2-1.9.jar                         | 4ffa87db52cf086d00ecc4853a929367b1c39b5c |
	| LC    | inventorytweaks           | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                                    | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| LC    | ironbackpacks             | 1.12.2-3.0.8-12          | IronBackpacks-1.12.2-3.0.8-12.jar                           | None                                     |
	| LC    | ironchest                 | 1.12.2-7.0.59.842        | ironchest-1.12.2-7.0.59.842.jar                             | None                                     |
	| LC    | jaopca                    | 1.12.2-2.2.8.101         | JAOPCA-1.12.2-2.2.8.101.jar                                 | None                                     |
	| LC    | oredictinit               | 1.12.2-2.2.1.71          | JAOPCA-1.12.2-2.2.8.101.jar                                 | None                                     |
	| LC    | jeibees                   | 0.9.0.5                  | jeibees-0.9.0.5-mc1.12.2.jar                                | None                                     |
	| LC    | jepb                      | 1.2.1                    | jepb-1.12-1.2.1.jar                                         | None                                     |
	| LC    | justenoughbuttons         | 1.12-1.2                 | justenoughbuttons-1.12.2-1.2.3.jar                          | None                                     |
	| LC    | jee                       | 1.0.6                    | JustEnoughEnergistics-1.12.2-1.0.6.jar                      | None                                     |
	| LC    | justenoughreactors        | 1.1.3.61                 | JustEnoughReactors-1.12.2-1.1.3.61.jar                      | 2238d4a92d81ab407741a2fdb741cebddfeacba6 |
	| LC    | lex                       | 1.0.8                    | LibEx-1.12.2-1.0.8.jar                                      | None                                     |
	| LC    | mcmultipart               | 2.5.3                    | MCMultiPart-2.5.3.jar                                       | None                                     |
	| LC    | morpheus                  | 1.12.2-3.5.106           | Morpheus-1.12.2-3.5.106.jar                                 | None                                     |
	| LC    | mrtjpcore                 | 2.1.3.35                 | MrTJPCore-1.12.2-2.1.3.35-universal.jar                     | None                                     |
	| LE    | nex                       | 2.0.8                    | NetherEx-1.12.2-2.0.8.jar                                   | None                                     |
	| L     | pneumaticcraft            | 1.12.2-0.10.5-346        | pneumaticcraft-repressurized-1.12.2-0.10.5-346.jar          | None                                     |
	| L     | projectred-core           | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-Base.jar                         | None                                     |
	| L     | projectred-integration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar                  | None                                     |
	| L     | projectred-transmission   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-integration.jar                  | None                                     |
	| L     | projectred-fabrication    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-fabrication.jar                  | None                                     |
	| L     | projectred-illumination   | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-lighting.jar                     | None                                     |
	| L     | projectred-expansion      | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                   | None                                     |
	| L     | projectred-relocation     | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                   | None                                     |
	| L     | projectred-transportation | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-mechanical.jar                   | None                                     |
	| L     | projectred-exploration    | 4.9.1.92                 | ProjectRed-1.12.2-4.9.1.92-world.jar                        | None                                     |
	| L     | redstonearsenal           | 2.6.2                    | RedstoneArsenal-1.12.2-2.6.2.17-universal.jar               | None                                     |
	| L     | thermaldynamics           | 2.5.4                    | ThermalDynamics-1.12.2-2.5.4.18-universal.jar               | None                                     |
	| L     | simplyjetpacks            | 2.2.11.64                | SimplyJetpacks2-1.12.2-2.2.11.64.jar                        | None                                     |
	| L     | spiceoflife               | 1.3.12                   | SpiceOfLife-mc1.12-1.3.12.jar                               | None                                     |
	| L     | storagedrawers            | 1.12-5.3.5               | StorageDrawers-1.12.2-5.3.8.jar                             | None                                     |
	| L     | storagedrawersextra       | @VERSION@                | StorageDrawersExtras-1.12-3.1.0.jar                         | None                                     |
	| L     | thaumicenergistics        | 2.2.2                    | thaumicenergistics-2.2.2.jar                                | None                                     |
	| L     | thermalcultivation        | 0.3.2                    | ThermalCultivation-1.12.2-0.3.2.11-universal.jar            | None                                     |
	| L     | thermalinnovation         | 0.3.2                    | ThermalInnovation-1.12.2-0.3.2.11-universal.jar             | None                                     |
	| L     | tcomplement               | ${version}               | TinkersComplement-1.12.2-0.3.2.jar                          | None                                     |
	| L     | tinkertoolleveling        | 1.12.2-1.1.0.DEV.b23e769 | TinkerToolLeveling-1.12.2-1.1.0.jar                         | None                                     |
	| L     | wrcbe                     | 2.3.1                    | WR-CBE-1.12.2-2.3.1.30-universal.jar                        | None                                     |
	| L     | nucleus                   | 1.10.0-S7.1              | Nucleus-1.10.0-S7.1-MC1.12.2-plugin.jar                     | None                                     |
	| L     | boop                      | 1.6.2                    | Boop-1.6.2.jar                                              | None                                     |
	| L     | magibridge                | 2.7                      | MagiBridge-API7-2.7.jar                                     | None                                     |
	| L     | worldedit                 | 6.1.9-SNAPSHOT           | worldedit-sponge-6.1.9-SNAPSHOT-dist.jar                    | None                                     |
	| L     | teslacorelib_registries   | 1.0.15                   | tesla-core-lib-1.12.2-1.0.15.jar                            | None                                     |
	| L     | wrapup                    | 1.12-1.1.3               | WrapUp-1.12-1.1.3.jar                                       | None                                     |

	Loaded coremods (and transformers): 
IELoadingPlugin (ImmersiveEngineering-core-0.12-89.jar)
  blusunrize.immersiveengineering.common.asm.IEClassTransformer
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
SpongeCoremod (spongeforge-1.12.2-2825-7.1.6-RC3694.jar)
  org.spongepowered.common.launch.transformer.SpongeSuperclassTransformer
AppleCore (AppleCore-mc1.12.2-3.2.0.jar)
  squeek.applecore.asm.TransformerModuleHandler
ForgelinPlugin (Forgelin-1.8.2.jar)
  
Quark Plugin (Quark-r1.5-149.jar)
  vazkii.quark.base.asm.ClassTransformer
	AE2 Version: stable rv6-stable-6 for Forge 14.23.5.2768
	Pulsar/natura loaded Pulses: 
		- NaturaCommons (Enabled/Forced)
		- NaturaOverworld (Enabled/Not Forced)
		- NaturaNether (Enabled/Not Forced)
		- NaturaDecorative (Enabled/Not Forced)
		- NaturaTools (Enabled/Not Forced)
		- NaturaEntities (Enabled/Not Forced)
		- NaturaOredict (Enabled/Forced)
		- NaturaWorld (Enabled/Not Forced)

	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- wailaIntegration (Enabled/Not Forced)

	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge,sponge'
	Type: Dedicated Server (map_server.txt)
```

**Comment by LogicTechCorp** [comment] 2020-04-15 23:43
This issue has been fixed in newer versions.

**Closed as completed by LogicTechCorp** 2020-04-15 23:43 UTC
